# Generated by Django 5.1 on 2024-08-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
